language: cpp
env:
  - CMAKE_COMPILATION_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/clang++-3.5 -DCMAKE_C_COMPILER=/usr/bin/clang-3.5 -DBOOST_ROOT=/opt/boost"
  - CMAKE_COMPILATION_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9 -DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DBOOST_ROOT=/opt/boost"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl https://www.tamersaadeh.com/diana/deb/pubkey.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://www.tamersaadeh.com/diana/deb/ all main" > /etc/apt/sources.list.d/team-diana.list'
  - sudo apt-get update
  - sudo apt-get install g++-4.9 
  - sudo apt-get install clang-3.5
  - sudo apt-get install boost-all boost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_COMPILATION_FLAGS
  - make

script:
  - make test

branches:
  only:
    - master

notifications:
  email: true

os:
  - linux
