language: cpp
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - curl https://www.tamersaadeh.com/diana/deb/pubkey.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://www.tamersaadeh.com/diana/deb/ all main" > /etc/apt/sources.list.d/team-diana.list'
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - sudo apt-get install boost-all boost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make test

branches:
  only:
    - master

notifications:
  email: true

os:
  - linux
