language: cpp
compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - cd build
  - make test

branches:
  only:
    - master

notifications:
  email: true

os:
  - linux
